title: Optimistic Cloud

services:
  Optimistic Cloud:
    - title: Immich
      description: Photo and Video management solution
      link: https://immich.optimistic.cloud
      icon:
        name: simple-icons:immich
        wrap: true
        color: '#4250AF'
      status:
        enabled: false
      tags:
        - h610i
    - title: Vaultwarden
      description: Password manager
      link: https://vaultwarden.optimistic.cloud
      icon:
        name: simple-icons:vaultwarden
        wrap: true
        color: '#000000'
      status:
        enabled: false
      tags:
        - m700
    - title: Gitea
      description: Git with a cup of tea!
      link: https://git.optimistic.cloud
      icon:
        name: simple-icons:gitea
        wrap: true
        color: '#609926'
      status:
        enabled: false
      tags:
        - m700
    - title: Opengist
      description: Self-hosted pastebin powered by Git
      link: https://gist.optimistic.cloud
      icon:
        url: https://raw.githubusercontent.com/thomiceli/opengist/master/public/img/opengist.svg
      status:
        enabled: false
      tags:
        - m700
    - title: Pocket ID
      description: Identity provider
      link: https://id.optimistic.cloud
      icon:
        url: https://cdn.jsdelivr.net/gh/selfhst/icons/webp/pocket-id.webp
      status:
        enabled: false
      tags:
        - m700

    - title: Invidious
      description: YouTube
      link: https://invidious.optimistic.cloud
      icon:
        name: simple-icons:invidious
        wrap: true
        color: '#00B6F0'
      status:
        enabled: false
      tags:
        - m700

    - title: Wallos
      description: Subscription Tracker
      link: https://wallos.optimistic.cloud
      icon:
        url: https://cdn.jsdelivr.net/gh/selfhst/icons/webp/wallos.webp
      status:
        enabled: false
      tags:
        - m700

    - title: Garage
      description: High Performance Object Storage
      link: https://garage.optimistic.cloud
      icon:
        url: https://cdn.jsdelivr.net/gh/selfhst/icons/webp/garage.webp
      status:
        enabled: false
      tags:
        - h610i
    - title: Jellyfin
      description: The Free Software Media System
      link: https://jellyfin.optimistic.cloud
      icon:
        url: https://cdn.jsdelivr.net/gh/selfhst/icons/webp/jellyfin.webp
      status:
        enabled: false
      tags:
        - m700

  App Configuration:
    - title: Vaultwarden Admin
      description: Administration for Vaultwarden
      link: https://vaultwarden.optimistic.cloud/admin
      icon:
        name: simple-icons:vaultwarden
        wrap: true
        color: '#000000'
      status:
        enabled: false
      tags:
        - Admin
        - m700

  Infrastructure:
    - title: Adguard Home (ns1)
      description: Network-wide ads & trackers blocking DNS server
      link: https://ns1.optimistic.cloud
      icon:
        name: simple-icons:adguard
        wrap: true
        color: '#68BC71'
      status:
        enabled: false
      tags:
        - rpi02
    - title: Adguard Home (ns2)
      description: Network-wide ads & trackers blocking DNS server
      link: https://ns2.optimistic.cloud
      icon:
        name: simple-icons:adguard
        wrap: true
        color: '#68BC71'
      status:
        enabled: false

    - title: Dozzle
      description: Realtime log viewer for containers
      link: https://dozzle.optimistic.cloud
      icon:
        url: https://cdn.jsdelivr.net/gh/selfhst/icons/webp/dozzle.webp
      status:
        enabled: false
      tags:
        - m700
    - title: Beszel
      description: Simple, lightweight server monitoring
      link: https://beszel.optimistic.cloud
      icon:
        url: https://cdn.jsdelivr.net/gh/selfhst/icons/webp/beszel.webp
      status:
        enabled: false
      tags:
        - m700
    - title: Beszel vps
      description: Simple, lightweight server monitoring
      link: https://beszel-vps.optimistic.cloud
      icon:
        url: https://cdn.jsdelivr.net/gh/selfhst/icons/webp/beszel.webp
      status:
        enabled: false
      tags:
        - vps
  TrueNAS:
    - title: TrueNAS
      description: Admin Dashboard
      link: https://nas.optimistic.cloud:444
      icon:
        name: simple-icons:truenas
        wrap: true
        color: '#0095D5'
      status:
        enabled: false
      tags:
        - Admin
        - h610i
    - title: TrueNAS API
      description: API docs
      link: https://nas.optimistic.cloud:444/api/docs/
      icon:
        name: simple-icons:swagger
        wrap: true
        color: '#85EA2D'
      status:
        enabled: false
      tags:
        - h610i
    - title: TrueNAS (Replication)
      description: Admin Dashboard
      link: https://192.168.188.166
      icon:
        name: simple-icons:truenas
        wrap: true
        color: '#0095D5'
      status:
        enabled: false
      tags:
        - Admin
        - optiplex-3060
    - title: TrueNAS API
      description: API docs
      link: https://192.168.188.166/api/docs/
      icon:
        name: simple-icons:swagger
        wrap: true
        color: '#85EA2D'
      status:
        enabled: false
      tags:
        - optiplex-3060

  Infrastructure (External):
    - title: Healthchecks.io (external)
      description: Cron job monitoring
      link: https://healthchecks.io
      icon:
        url: https://cdn.jsdelivr.net/gh/selfhst/icons/webp/healthchecks.webp
      status:
        enabled: false
    - title: Healthchecks.io
      description: Cron job monitoring
      link: https://hc.optimistic.cloud
      icon:
        url: https://cdn.jsdelivr.net/gh/selfhst/icons/webp/healthchecks.webp
      status:
        enabled: false
      tags:
        - vps
    - title: GitHub
      description: GitHub organization
      link: https://github.com/optimistic-cloud
      icon:
        name: simple-icons:github
        wrap: true
        color: '#181717'
      status:
        enabled: false
    - title: smtp2go
      description: SMTP relay
      link: https://smtp2go.com
      icon:
        name: simple-icons:mailchimp
        wrap: true
        color: '#FFE01B'
      status:
        enabled: false
    - title: Status Page
      description: Status page for Optimistic Cloud services
      link: https://status.optimistic.cloud
      status:
        enabled: false
      tags:
        - Infrastructure
    - title: Documentation
      description: Documentation for Optimistic Cloud services
      link: https://documentation.optimistic.cloud
      status:
        enabled: false
      tags:
        - Infrastructure

  Rework:
    - title: YouTrack
      description: Project management
      link: https://youtrack.optimistic.cloud
      icon:
        url: https://resources.jetbrains.com/storage/products/company/brand/logos/YouTrack_icon.svg
      status:
        enabled: false
      tags:
        - m700
    - title: Papra
      description: Document management
      link: https://documents.optimistic.cloud
      icon:
        url: https://cdn.jsdelivr.net/gh/selfhst/icons/webp/papra.webp
      status:
        enabled: false
      tags:
        - m700
    - title: Redlib
      description: Reddit
      link: https://redlib.optimistic.cloud
      icon:
        url: https://cdn.jsdelivr.net/gh/selfhst/icons/webp/redlib.webp
      status:
        enabled: false
      tags:
        - m700
    - title: Traefik Dashboard
      description: reverse proxy and load balancer
      link: https://traefik.optimistic.cloud
      icon:
        url: https://cdn.jsdelivr.net/gh/selfhst/icons/webp/traefik.webp
      status:
        enabled: false
      tags:
        - m700

    - title: Minio
      description: High Performance Object Storage
      link: https://minio.tryrocket.cloud
      icon:
        name: simple-icons:minio
        wrap: true
        color: '#C72E49'
      status:
        enabled: false
      tags:
        - h610i

tags:
  - name: Home
    color: green
  - name: Infrastructure
    color: blue
  - name: Admin
    color: red
  - name: m700
    color: lime
  - name: h60i
    color: orange
  - name: optiplex-3060
    color: fuchsia
  - name: vps
    color: yellow
  - name: rpi02
    color: teal
# red, orange, amber, yellow, lime, green, emerald, teal, cyan, sky, blue, indigo, violet, purple, fuchsia, pink, rose
